Repository mucsci-students/2020fa-420-CovidSurvivors, pull requests merged in 2020-11, with the labels that each got.

#210 Argument Checking
  code/CLI/CLIEditor.py
Labels: bug, refactor

#211 Fixed bug where renaming a class does not change the name in the rela…
  code/models/UMLModel.py
  code/unit-tests/test_UMLModel.py
Labels: bug

#212 GUI Parameters & Fixed index error
  code/WebApp/main.py
  code/WebApp/static/js/myscripts.js
  code/WebApp/templates/card.html
  code/WebApp/templates/modalForm.html
  code/command/command.py
  code/data/__WorkingModel__.json
Labels: bug, enhancement

#215 Update LICENSE
  LICENSE
Labels: documentation

#214 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
Labels: documentation

#213 Update README.md
  README.md
Labels: documentation

#216 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#234 Tab Completion for save_model/load_model
  code/CLI/CLIEditor.py
  code/CLI/__pycache__/CLIEditor.cpython-38.pyc
  code/CLI/__pycache__/CommandData.cpython-38.pyc
  code/CLI/__pycache__/__init__.cpython-38.pyc
  code/command/__pycache__/command.cpython-38.pyc
Labels: enhancement

#237 create method with protected visibility in the gui
  code/WebApp/static/js/myscripts.js
  code/WebApp/templates/modalForm.html
Labels: enhancement

#238 Multi model
  code/WebApp/main.py
  code/WebApp/static/css/style.css
  code/WebApp/static/js/myscripts.js
  code/WebApp/templates/base.html
  code/WebApp/templates/createClassModal.html
  code/WebApp/templates/createModelModal.html
  code/WebApp/templates/dashboard.html
  code/WebApp/templates/deleteClassModal.html
  code/WebApp/templates/editClassModal.html
  code/WebApp/templates/loadFileModal.html
  code/WebApp/templates/models.html
  code/command/command.py
  code/models/UMLModel.py
  code/server-data/I was uploaded :).json
  code/server-data/__temp__.json
  code/server-data/badfile.json
  code/server-data/download.json
  code/server-data/emptyfile.json
  code/server-data/emptymodel.json
  code/server-data/multi word model name.json
  code/server-data/saved.json
  code/server-data/tempdata.json
  code/server-data/test.json
  code/server-data/toast.json
  code/server-data/toast2.json
Labels: enhancement, refactor

#243 Implemented rename and delete models
  code/WebApp/main.py
  code/WebApp/static/js/myscripts.js
  code/WebApp/templates/deleteModelModal.html
  code/WebApp/templates/models.html
  code/WebApp/templates/renameModelModal.html
  code/models/UMLModel.py
  code/server-data/I was uploaded :).json
  code/server-data/download.json
  code/server-data/multi word model name.json
  code/server-data/myNameChanged.json
  code/server-data/newmodel.json
  code/server-data/toast2.json
Labels: enhancement

#249 fixed UMLModel loading error
  code/models/UMLModel.py
  code/server-data/UMLEditor.json
Labels: bug

#251 Implemented redrawing arrows when cards are moved
  code/WebApp/static/css/style.css
  code/WebApp/static/js/myscripts.js
  code/WebApp/templates/dashboard.html
  code/server-data/This is cool :D.json
  code/server-data/UMLEditor.json
  code/server-data/tempdata.json
  code/server-data/test.json
Labels: enhancement

#261 Added tests for saving and loading
  code/models/UMLClass.py
  code/models/UMLModel.py
  code/unit-tests/test_UMLModel.py
Labels: testing

#262 added tests for UMLClass
  code/models/UMLClass.py
  code/unit-tests/test_UMLClass.py
Labels: testing

#270 fixed editted card from moving to 0,0
  code/command/command.py
  code/unit-tests/test_command.py
Labels: bug

#273 new create/edit/delete relationships controllers
  code/WebApp/main.py
  code/WebApp/static/css/style.css
  code/WebApp/static/js/myscripts.js
  code/WebApp/templates/card.html
  code/WebApp/templates/createClassModal.html
  code/WebApp/templates/createRelationshipModal.html
  code/WebApp/templates/dashboard.html
  code/WebApp/templates/editRelationshipForm.html
  code/WebApp/templates/editRelationshipModal.html
  code/WebApp/templates/modalForm.html
  code/command/command.py
  code/server-data/UMLEditor.json
  code/unit-tests/test_command.py
Labels: bug, enhancement

#274 fixed upload bug
  code/WebApp/main.py
Labels: bug
