Repository mucsci-students/2020fa-420-CovidSurvivors, pull requests merged in 2020-09, with the labels that each got.

#23 UMLModel
  code/UMLModel.py
Labels: enhancement

#24 UMLRelationship
  code/UMLRelationship.py
Labels: enhancement

#25 added UMLClass file
  code/UMLClass.py
Labels: enhancement

#22 UMLEditor
  code/UMLEditor.py
Labels: enhancement

#26 Initial setup
  code/UMLClass.py
  code/UMLEditor.py
  code/UMLModel.py
  code/UMLRelationship.py
Labels: documentation

#27 Help message
  code/CommandData.py
  code/UMLEditor.py
Labels: enhancement

#49 README for Sprint 1
  README.md
Labels: documentation

#52 Create relationships
  code/UMLModel.py
Labels: enhancement

#100 Execute overhaul
  code/CommandData.py
  code/UMLEditor.py
Labels: bug, enhancement, refactor

#97 Field and Method files
  code/UMLClass.py
  code/UMLField.py
  code/UMLMethod.py
  code/Visibility.py
Labels: enhancement

#103 Refactor Saving/Loading and Reworked Relationships
  code/CommandData.py
  code/RelationshipType.py
  code/UMLClass.py
  code/UMLField.py
  code/UMLMethod.py
  code/UMLModel.py
  code/UMLRelationship.py
  code/Visibility.py
  code/models/test.json
Labels: refactor

#98 EOF bug
  code/UMLEditor.py
Labels: bug

#105 List classes
  code/CommandData.py
  code/RelationshipType.py
  code/UMLModel.py
  code/UMLRelationship.py
Labels: enhancement

#106 Created template for GUI
  code/WebApp/main.py
  code/WebApp/static/css/bootstrap.min.css
  code/WebApp/static/css/style.css
  code/WebApp/static/jqueryui/jquery-ui.css
  code/WebApp/static/jqueryui/jquery-ui.js
  code/WebApp/static/jqueryui/jquery-ui.structure.css
  code/WebApp/static/jqueryui/jquery-ui.theme.css
  code/WebApp/static/js/bootstrap.min.js
  code/WebApp/static/js/jquery.js
  code/WebApp/static/js/jquery.min.js
  code/WebApp/static/js/myscripts.js
  code/WebApp/static/js/popper.min.js
  code/WebApp/templates/base.html
  code/WebApp/templates/card.html
  code/WebApp/templates/createClassModal.html
  code/WebApp/templates/dashboard.html
  code/WebApp/templates/deleteClassModal.html
  code/WebApp/templates/editClassModal.html
  code/WebApp/templates/loadFileModal.html
  code/__pycache__/CommandData.cpython-36.pyc
  code/__pycache__/UMLClass.cpython-36.pyc
  code/__pycache__/UMLModel.cpython-36.pyc
  code/__pycache__/UMLRelationship.cpython-36.pyc
Labels: enhancement
